print("Welcome to the Band Name Generator!\nWhat's the name of the city you grew up in?")
city = input()
print("What's your pets name?")
pet = input()
print("Your band name could be: " + city + " " + pet)